### ISSUE TITLE
custom side menu items

### ISSUE THREAD

**Issue by zyknow** [AvaloniaInside/Shell#10]
i want to custom side menu to this
![image](https://github.com/AvaloniaInside/Shell/assets/49929368/4363999b-5470-4ce2-8994-c479ad86bf86)

can i use like this to custom datetemplate
![image](https://github.com/AvaloniaInside/Shell/assets/49929368/140838f4-eaf0-4479-ac3d-2d03a26dc62b)

**Comment by OmidID** [comment]
Hello @zyknow 
Thanks for the input. Interesting that we have the same question today :)

https://github.com/AvaloniaInside/Shell/issues/8

It is better to keep the discussion there. We can share ideas to find the best solution.
