### ISSUE TITLE
In anroid，when textbox focus，UI extends to the status bar

### ISSUE THREAD

**Issue by suyana** [AvaloniaInside/Shell#22]
I use the built-in demo and add a textbox. When the textbox is in focus, the UI will extend to the status bar

Before：
![before](https://github.com/AvaloniaInside/Shell/assets/15610698/26b3dd65-77a8-4086-94d7-d42305d9e45d)

Focus TextBox After：
![after](https://github.com/AvaloniaInside/Shell/assets/15610698/c73e973e-3c70-4f70-966c-0a2dbd79fe08)

When I comment out the following code, this issue will not occur：
![jiejue](https://github.com/AvaloniaInside/Shell/assets/15610698/bd3dd3cf-da43-4220-829d-5fc5ad56bd71)

**Comment by OmidID** [comment]
Thanks for reporting the bug.

Is it reproducible on real device too?

**Comment by suyana** [comment]
I have tested it on a real device and this problem will not occur.
It always looks like image 2

> Thanks for reporting the bug.
> 
> Is it reproducible on real device too?
