### ISSUE TITLE
Unable to resolve 'Instance' - Intellisense / Compiler warns since it doesn't know that entity

### ISSUE THREAD

**Issue by PhilWeisz** [AvaloniaInside/Shell#24]
https://github.com/AvaloniaInside/Shell/blame/10d6d8c159ea76e2ade707c76c6a6a9bf3efa642/src/Example/ShellExample/ShellExample/Views/MainTabControl.axaml#L16

https://github.com/AvaloniaInside/Shell/blame/10d6d8c159ea76e2ade707c76c6a6a9bf3efa642/src/Example/ShellExample/ShellExample/Views/MainTabControl.axaml#L21

https://github.com/AvaloniaInside/Shell/blame/10d6d8c159ea76e2ade707c76c6a6a9bf3efa642/src/Example/ShellExample/ShellExample/Views/MainTabControl.axaml#L30

![image](https://github.com/AvaloniaInside/Shell/assets/122535935/d6b307e9-3380-49df-a73e-ad5e9a639e62)

**Comment by Yusuke1998** [comment]
Please, help! :(

**Comment by OmidID** [comment]
Hello,

By adding data type to the data template you can partially solve this issue.

![image](https://github.com/AvaloniaInside/Shell/assets/956077/58048a97-8cc7-4fd4-a428-88dd54755e10)


The type of Instance is object and basically it is the page already loaded. To have icon, i added a property of icon to each page. 
So in case to have avoid error on Icon too, in your app you can define a base class for your main page tabs and use the base type as style and use it in template design.
