### ISSUE TITLE
Allow for ViewModel navigation

### ISSUE THREAD

**Issue by gentledepp** [AvaloniaInside/Shell#25]
In my viewmodels, I would like to kick of navigation by 
- injecting `INavigator`
- and calling `NaviateToAsync(string path, object argument)`

As I see it, this is not implemented out of the box.
Also, I am not sure it has to be part of the Shell.

But: Maybe you can give some advice on how one should approach this.

Do you have any thoughts on this? Or is this of no value/interest to you? :-)

**Comment by OmidID** [comment]
Already cover in the example here: https://github.com/AvaloniaInside/Shell/issues/26
