### ISSUE TITLE
Vanilla MVVM

### ISSUE THREAD

**Issue by Petrarca181** [AvaloniaInside/Shell#3]
Hello, very cool project! Would be nice to have possibility to decide if use reactive or community mvvm.

**Comment by OmidID** [comment]
Hello @Petrarca181 , 
Thanks :)
You can use any MVVM pattern you wish. The project used binding and I didn't integrate any specific library. You can adapt the binding with any library you need.

**Comment by Petrarca181** [comment]
I'm trying to compile right now, blank avalonia app, mainview has only blank shell.  Can't compile because shell wants InavigationService.

**Comment by OmidID** [comment]
Did you call UseShell?

https://github.com/AvaloniaInside/Shell/blob/main/src/Example/ShellExample/ShellExample.Desktop/Program.cs#L23

**Comment by Petrarca181** [comment]
![Screenshot (6)](https://github.com/AvaloniaInside/Shell/assets/54235138/4d9c8ce2-d18f-4627-b973-2181997551bc)
![Screenshot (7)](https://github.com/AvaloniaInside/Shell/assets/54235138/e7fc12f1-14c2-41df-91b6-05a545c314ac)

**Comment by OmidID** [comment]
For me, there is no reason why this is not working. Do you have the possibility to share your example app so that i can check why this is not working?
And can you try with deep clean and run it again too?

**Comment by crobibero** [comment]
I had to do the following in order to use both `Microsoft.Extensions.DependencyInjection` and `AvaloniaInside.Shell`. I had to do this because this shell library relies on `Splat` for dependency location.

Snippet:
```c#
private static void AddNavigation(this IServiceCollection services)
{
    services.AddSingleton<INavigationRegistrar, NavigationRegistrar>();
    Locator.CurrentMutable.Register(() => App.Current.ServiceProvider.GetRequiredService<INavigationRegistrar>());

    services.AddSingleton<IPresenterProvider, PresenterProvider>();
    Locator.CurrentMutable.Register(() => App.Current.ServiceProvider.GetRequiredService<IPresenterProvider>());

    services.AddSingleton<INavigationViewLocator, DefaultNavigationViewLocator>();
    Locator.CurrentMutable.Register(() => App.Current.ServiceProvider.GetRequiredService<INavigationViewLocator>());

    services.AddSingleton<INavigationUpdateStrategy>(provider => new DefaultNavigationUpdateStrategy(provider.GetRequiredService<IPresenterProvider>()));
    Locator.CurrentMutable.Register(() => App.Current.ServiceProvider.GetRequiredService<INavigationUpdateStrategy>());

    services.AddSingleton<INavigator>(provider =>
    {
        var navigationRegistrar = provider.GetRequiredService<INavigationRegistrar>();
        return new Navigator(
            navigationRegistrar,
            new RelativeNavigateStrategy(navigationRegistrar),
            provider.GetRequiredService<INavigationUpdateStrategy>(),
            provider.GetRequiredService<INavigationViewLocator>());
    });
    Locator.CurrentMutable.Register(() => App.Current.ServiceProvider.GetRequiredService<INavigator>());
}
```

Full example: https://github.com/crobibero/jellyfin-client-maui/blob/master/src/Jellyfin.Avalonia/Program.cs#L78-L102

**Comment by OmidID** [comment]
Thanks @crobibero 
Let's say most of the Avalonia base controls are the same. Because Shell can customize very well, we needed to have some services and the best place to resolve them, is the default Avalonia DI.

**Comment by OmidID** [comment]
No activation for long time. I will close this ticket.
