### ISSUE TITLE
Call from invalid thread

### ISSUE THREAD

**Issue by cedric56** [AvaloniaInside/Shell#31]
Hi, i have transpose the sample to my project but each time i click on a control i have got a Call from invalid thread. I fall on Dispatcher issue.  What i done wrong? I see this in trhe output

![image](https://github.com/AvaloniaInside/Shell/assets/26410109/4788d9ae-cdfa-4bb4-8a9e-b2762646cb55)

**Comment by cedric56** [comment]
I forgot to UseReactiveUI

**Comment by OmidID** [comment]
Hello @cedric56 
Do you still need help? 
Thanks

**Comment by cedric56** [comment]
no thanks @OmidID
