### ISSUE TITLE
Getting Out of order buffers detected for RequestedLayerState error when i run the app

### ISSUE THREAD

**Issue by namacctforcicd** [AvaloniaInside/Shell#35]
Good day, when I try to run my app I'm working on, I get "Out of order buffer detected" error.
<img width="1470" alt="Screenshot 2024-07-10 at 4 55 01 AM" src="https://github.com/AvaloniaInside/Shell/assets/119373969/2d605122-30ad-471e-a8c3-40e56c39ec8a">

If you need more info, please let me know. Thank you. 

email is nnamdiwill@gmail.com

**Comment by OmidID** [comment]
Not related to this project.
