### ISSUE TITLE
Navigator.BackAsync exception when getting back from modal to another modal

### ISSUE THREAD

**Issue by Mateusz-Nejman** [AvaloniaInside/Shell#64]
Hi! I have some modals and for one case I have to open one modal from another. It work fine, but when I use Navigator.BackAsync, I'm getting exception:
`The control Pixed.Application.Windows.PaletteWindow (Content = DockPanel) already has a visual parent AvaloniaInside.Shell.StackContentView (Name = PART_Modal) while trying to add it as a child of AvaloniaInside.Shell.StackContentView (Name = PART_ContentView).'`
PaletteWindow is a parent modal. Exception is thrown in [StackContentView::PushViewAsync#L64](https://github.com/AvaloniaInside/Shell/blob/develop/src/AvaloniaInside.Shell/StackContentView.cs#L64). I locally added catch to try/finally for ignoring this exception and it works, but its temporary workaround.

**Comment by OmidID** [comment]
Hello @Mateusz-Nejman 
Thanks for reporting the error. I can see line above there is a check to remove and add again the control if already has a parent. 
It can help, if you can provide an real example or solution that I can run and debug.
Thanks.

**Comment by Mateusz-Nejman** [comment]
Repro repository: [https://github.com/Mateusz-Nejman/AvaloniaInside.Shell-Issue-64](https://github.com/Mateusz-Nejman/AvaloniaInside.Shell-Issue-64)
