### ISSUE TITLE
Proposal to better navigation

### ISSUE THREAD

**Issue by FabricioGonzalez** [AvaloniaInside/Shell#8]
I have downloaded your project. I found it very interesting. Having something like the concept of shell.
I have a situation where your project may be applied to achieve navigation.
But I need to have nested side menu items.
I will work to modify and then send a pull request.

**Comment by OmidID** [comment]
Hello @FabricioGonzalez 
Thanks for the input. I mainly took the idea from [Xamarin/Maui Shell](https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/shell/flyout). As you see nested menu item is not supported by Xamarin too. I think you can simply ignore the menu item and create your own Menu user control and place it into the Side menu Contents.
Very rare possible you can find a sub-item in mobile apps. 
What I suggest, is to think about what is the needs of it first and please share with me some ideas and if we need to improve it, why not.
Thanks again.

**Comment by FabricioGonzalez** [comment]
I will think. I am currently using the shell on windows. That is a good idea too. Changing the body of the side menu. That can do what I need for now.

**Comment by FabricioGonzalez** [comment]
It's a good idea to make avalonia take good ideas from other frameworks. I have used many UI frameworks from .net environment. And Avalonia was the one I most liked.
On functionalities, seems to be the best one. On visuals, I think Winui 3 is the best. but the way it work. Reminds me of UWP. and I really deslike  UWP. So, what we can do is to transform Avalonia on the best tool we can

**Comment by buzzware** [comment]
Please see 
https://github.com/buzzware/pelican_dev
for me ideas on mobile routing.
In particular; 
1) most mobile routers make the mistake of requiring that all routing urls be declared up front when in fact potential route segments should be declared, and the route be constructed at runtime from segments.
2) each segment needs its own parameters (and I argue options)

**Comment by OmidID** [comment]
> Please see https://github.com/buzzware/pelican_dev for my ideas on mobile routing. In particular;
> 
> 1. most mobile routers make the mistake of requiring that all routing urls be declared up front when in fact potential route segments should be declared, and the route be constructed at runtime from segments.
> 2. each segment needs its own parameters (and I argue options)
> 3. redirects, so that you can link buttons everywhere to /home, and redirect /home dynamically to somewhere else

Hello @buzzware ,

Long time pass from this request. As I do a cleanup in issue list, I answerting this comment as well.

1. Today, registrar service allow you to dynamically add, remove route registration
2. This one still not clear for me. But yes, each segment can has it own arguments.
3. This is possible today using attached property from Navigator.To 

Overall, most of the functionality of shell can be easily replaced because it is based on strategy or abstract pattern.

Something else that I can help on this thread?
